server:
  port: 7900

hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    packagesToScan: /
    hbm2ddl:
      auto: update

logging:
  level:
    liquibase: INFO

spring:
  profiles:
    active: @spring.profiles.active@

  liquibase:
    enabled: false





